services:

  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - habrdb-data:/var/lib/postgresql/data

  bot:
    image: nobodyknowsdotcom/pigeonbot:latest
    environment:
      APP_BOT_NAME: ${BOT_NAME}
      APP_BOT_TOKEN: ${BOT_TOKEN}
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    ports:
      - "8080:8080"

volumes:
  habrdb-data: